use crate::core::mcu_db::McuInfo;

pub const NXP_MCUS: &[McuInfo] = &[
    McuInfo {
        id: "k10d",
        part_number: "MK10DN512VLL10",
        define: "MK10D7",
        core: "cortex-m4",
        fpu: "soft",
        clock_mhz: 100,
        flash_kb: 512,
        ram_kb: 128,
        family: "kinetis",
        series: "K10",
        vendor: "nxp",
    },
    McuInfo {
        id: "k12",
        part_number: "MK12DN512VLH5",
        define: "MK12D5",
        core: "cortex-m4",
        fpu: "soft",
        clock_mhz: 50,
        flash_kb: 512,
        ram_kb: 128,
        family: "kinetis",
        series: "K12",
        vendor: "nxp",
    },
    McuInfo {
        id: "k22f",
        part_number: "MK22FX512VLL12",
        define: "MK22F12",
        core: "cortex-m4",
        fpu: "soft",
        clock_mhz: 120,
        flash_kb: 512,
        ram_kb: 128,
        family: "kinetis",
        series: "K22",
        vendor: "nxp",
    },
    McuInfo {
        id: "k64",
        part_number: "MK64FN1M0VLL12",
        define: "MK64F12",
        core: "cortex-m4",
        fpu: "soft",
        clock_mhz: 120,
        flash_kb: 1024,
        ram_kb: 256,
        family: "kinetis",
        series: "K64",
        vendor: "nxp",
    },
    McuInfo {
        id: "k66",
        part_number: "MK66FN2M0VMD18",
        define: "MK66F18",
        core: "cortex-m4",
        fpu: "hard",
        clock_mhz: 180,
        flash_kb: 2048,
        ram_kb: 256,
        family: "kinetis",
        series: "K66",
        vendor: "nxp",
    },
];
