use anyhow::{Context, Result};
use colored::*;

use crate::core::{config, project};
use crate::utils::paths;

pub fn run(ci: bool, force: bool) -> Result<()> {
    // 1. Ensure ~/.embtool directories exist
    paths::ensure_dirs().context("Failed to create embtool directories")?;

    // 2. Find and load embtool.toml
    let project_path = project::find_project()?;
    let project_dir = project_path.parent().unwrap();
    let proj = project::load(&project_path)?;

    println!("{} Reading embtool.toml...", "🔍".bold());
    println!("   Project: {}", proj.project.name.cyan());
    println!(
        "   MCU: {} ({})",
        proj.target.mcu.cyan(),
        proj.target.core
    );
    println!(
        "   Toolchain: {}",
        proj.toolchain.id().cyan()
    );
    println!();

    // 3. Load global config
    let _global_config = config::load()?;
    let is_ci = ci || config::is_ci();

    // 4. Check if toolchain is installed
    let tc_path = paths::toolchain_path(&proj.toolchain.vendor, &proj.toolchain.version)?;
    let gcc_name = if cfg!(windows) {
        "arm-none-eabi-gcc.exe"
    } else {
        "arm-none-eabi-gcc"
    };

    if tc_path.join("bin").join(gcc_name).exists() && !force {
        println!(
            "{} Toolchain {} already installed at {}",
            "✅".bold(),
            proj.toolchain.id().green(),
            tc_path.display()
        );
    } else {
        println!(
            "{} Toolchain {} not found locally.",
            "📦".bold(),
            proj.toolchain.id().yellow()
        );
        if is_ci {
            println!("   CI mode: will auto-install");
        }
        // TODO: Call toolchain_manager::install() when implemented
        println!(
            "   {}",
            "(toolchain install not yet implemented — run 'embtool toolchain install' manually)"
                .dimmed()
        );
        println!();
    }

    // 5. Generate arm-toolchain.cmake
    let cmake_path = project_dir.join("arm-toolchain.cmake");
    if cmake_path.exists() && !force {
        println!(
            "{} arm-toolchain.cmake already exists (use --force to overwrite)",
            "ℹ️ ".bold()
        );
    } else {
        generate_toolchain_cmake(&cmake_path, &proj)?;
        println!(
            "{} Generated arm-toolchain.cmake",
            "🔧".bold()
        );
    }

    println!();
    println!(
        "{} Setup complete! Run '{}' to build.",
        "✅".bold(),
        "embtool build".green()
    );

    Ok(())
}

fn generate_toolchain_cmake(
    path: &std::path::Path,
    proj: &project::ProjectConfig,
) -> Result<()> {
    let toolchain_id = proj.toolchain.id();

    let content = format!(
        r#"# Auto-generated by embtool - DO NOT EDIT
# Toolchain: {vendor} ARM GCC {version}
# Run 'embtool setup' to regenerate

cmake_minimum_required(VERSION 3.20)

# embtool managed toolchain path
if(WIN32)
    set(EMBTOOL_HOME "$ENV{{USERPROFILE}}/.embtool")
else()
    set(EMBTOOL_HOME "$ENV{{HOME}}/.embtool")
endif()

set(EMBTOOL_TOOLCHAIN_ID "{toolchain_id}")
set(ARM_TOOLCHAIN_ROOT "${{EMBTOOL_HOME}}/toolchains/${{EMBTOOL_TOOLCHAIN_ID}}")
set(ARM_TOOLCHAIN_PATH "${{ARM_TOOLCHAIN_ROOT}}/bin/")

set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_C_COMPILER "${{ARM_TOOLCHAIN_PATH}}arm-none-eabi-gcc")
set(CMAKE_CXX_COMPILER "${{ARM_TOOLCHAIN_PATH}}arm-none-eabi-g++")
set(CMAKE_ASM_COMPILER "${{ARM_TOOLCHAIN_PATH}}arm-none-eabi-gcc")
set(CMAKE_AR "${{ARM_TOOLCHAIN_PATH}}arm-none-eabi-ar")
set(CMAKE_OBJCOPY "${{ARM_TOOLCHAIN_PATH}}arm-none-eabi-objcopy" CACHE INTERNAL "")
set(CMAKE_SIZE "${{ARM_TOOLCHAIN_PATH}}arm-none-eabi-size" CACHE INTERNAL "")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
"#,
        vendor = proj.toolchain.vendor.to_uppercase(),
        version = proj.toolchain.version,
        toolchain_id = toolchain_id,
    );

    std::fs::write(path, content)
        .with_context(|| format!("Failed to write {}", path.display()))?;

    Ok(())
}
